project_id = "sdoidtzxaxpmhgrocpah"

[functions.admin-create-student]
verify_jwt = true

[functions.create-super-admin]
verify_jwt = false

[functions.admin-create-organization]
verify_jwt = true

[functions.sync-auth-user]
verify_jwt = false