[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "campus-link"

[services.variables]
NODE_ENV = "production"
PORT = "4173"