// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdoidtzxaxpmhgrocpah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkb2lkdHp4YXhwbWhncm9jcGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNjU1OTcsImV4cCI6MjA2ODY0MTU5N30.8OxH3c7V0ZAWLT6KDIGhXgwHY2GBXANjiFh6gk6ACGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});